### ISSUE TITLE
Create a reporting style easier to post process with UNIX tools

### ISSUE THREAD

**Issue by phochste** [pkiraly/metadata-qa-marc#19]
The current report per record looks like:

```
Error in 'fol05882032 ':
	100$ind1 has invalid code: '2' (https://www.loc.gov/marc/bibliographic/bd100.html)
```

Could this be written in a format that can be easily processed with grep, cut,sort? E.g. where each line contains the record-id, field, value and documentation? E.g. 

```
fol05882032<tab>100$ind1<tab>invalid code<tab>2<tab>https://www.loc.gov/marc/bibliographic/bd100.html
```

**Comment by pkiraly** [comment]
I am checking the possibilities. The problem is that there are different error types, and not all has the same structure. For example sometimes the wrong code is part of a larger unit:

` contains an invalid code: 'h' in 'bh  '`

It means that 'b' and ' ' are acceptable, only 'h' is wrong. In this case, do you prefer

```
fol05882032<tab>006/01-04<tab>invalid code<tab>'h'<tab>https://www.loc.gov/marc/bibliographic/bd100.html
```
or
```
fol05882032<tab>006/01-04<tab>invalid code<tab>'h' in 'bh  '<tab>https://www.loc.gov/marc/bibliographic/bd100.html
```
?

**Comment by phochste** [comment]
The second some probably:

* record-id
* marc-path
* error-type
* error-string
* reference

**Comment by pkiraly** [comment]
It is done, you can test it with using the new --format parameter:

`-r [format]`, `--format [format]` format specification of the output. Possible values: `text` (default), `tab-separated` or `comma-separated`

**Comment by phochste** [comment]
Checked ! Thanks
